spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommandation
      database: airecommandation

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.vaibhav.microservices.aiservice.model.Activity
        spring.json.trusted.packages: "*"
    topic:
      name: activity-events

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:   # Corrected key from serviceUrl → service-url
      defaultZone: http://localhost:8761/eureka/
  instance:      # Added instance configuration
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

server:
  port: 8083
